HL7/cqf-measures

- pages/cql/BreastCancerScreening-7.2.000.cql
- pages/cql/ColorectalCancerScreening-7.2.000.cql
- pages/cql/Hemoglobin A1c Poor Control-7.2.000.CQL
CQL for Colorectal Cancer, Hemoglobin and Breast Cancer
> Add new CQL measures

- pages/glossary.md
Please review this pull request for GF#21937.
> Yh trackers

- pages/measure-conformance.md
- pages/using-cql.md
regarding null values as per resolution description of FHIR-24102
> FHIR-24102, FHIR-26561, FHIR-26564, FHIR-26456

- cql/EXMRatio.cql
- ig.json
- pages/_includes/modelinfo-library-cqfm-ex.html
- pages/examples.md
- pages/measure-conformance.md
- pages/terminology.md
- resources/conceptmap/conceptmap-aggregate-method.json
- resources/conceptmap/conceptmap-composite-measure-scoring.json
- resources/conceptmap/conceptmap-measure-scoring.json
- resources/conceptmap/conceptmap-measure-types.json
- resources/cqfmeasures.xml
- resources/library/Library-EXMModelInfoLibrary.json
- resources/measure/measure-publishable-exm.xml
- resources/profile-library-cqfm-spreadsheet.xml
- resources/profile-measure-cqfm-spreadsheet.xml
- resources/profile-modelinfo-library-cqfm-spreadsheet.xml
- resources/profile-ratio-measure-cqfm-spreadsheet.xml
Added Concept Maps for MeasureScoring, CompositeMeasureScoring, MeasureType & AggregateMethod. Included a section with story for HQMF Mapping
> FHIR-28210/28238/28239/28288/28290

- input/cqfmeasures.xml
- input/pages/extensions.md
- input/profiles/StructureDefinition-cqfm-pertinence.json
> Ig updates

- input/pages/quality-measurement-standards-landscape.md
- input/vocabulary/codesystem-quality-programs.json
> Ig changes

- input/pages/data-model-standards-landscape.md
FHIR-40189: No hyperlink for the reference to the HEDIS IG
> FHIR 40189 HEDIS IG reference

- templates/liquid/Measure.liquid
Download CQL link now conditionally shown based on Measure.library.exists()
> Conditional Download CQL link 

- input/pages/using-cql.md
https://jira.hl7.org/browse/FHIR-42922
> FHIR-42922 - Applied changes to using-cql

- input/pages/measure-conformance.md
Updated conformance requirement 3.4 to text provided in ticket
> FHIR-42894 - Updated conformance requirement 3.4 to text provided

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43638
> FHIR-43638: URL updated.

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43642
> FHIR-43642: Updated snippets

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43772
> Fixed table 3-1

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43775
> Removed unused commas in json snippet

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43645
> FHIR-43645: Denominator Exception

- input/pages/index.md
https://jira.hl7.org/browse/FHIR-44120
> FHIR-44120: Capitalize medicare and medicaid

- input/pages/introduction.md
https://jira.hl7.org/browse/FHIR-43682
> FHIR-43682: Renamed section 2.6

- input/vocabulary/codesystem-quality-programs-example.json
https://jira.hl7.org/browse/FHIR-44394
> FHIR-44394: CodeSystem Quality Program - add -example to the URL, and add Example to the name and title.

- input/vocabulary/valueset-quality-programs-example.json
https://jira.hl7.org/browse/FHIR-44400
> FHIR-44400: ValueSet Quality Program - add -example to the URL, and add Example to the name and title.

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43962
> FHIR-43962: add a note below table 3-1

- input/vocabulary/codesystem-quality-programs-example.json
https://jira.hl7.org/browse/FHIR-43323
> FHIR-43323: Remove code ep-ec from Quality Programs value set

- input/includes/menu.xml
- input/pages/index.md
https://jira.hl7.org/browse/FHIR-43622
> FHIR-43622: Aligned menu with 1.2

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-44991
> FHIR-44991: Updated media types/namespaces url

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43781
> FHIR-43781: Clarify ELM -> DataRequirements expectations

- input/profiles/StructureDefinition-cqfm-populationBasis.json
https://jira.hl7.org/browse/FHIR-43782
> FHIR-43782: Updated populationBasis extension description

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-44598
> FHIR-44598: Remove requirement

- input/pages/data-model-standards-landscape.md
https://jira.hl7.org/browse/FHIR-43428
> FHIR-43428: Updated eCR IG design considerations url

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-43781
> FHIR-43781: Updated oid to point at url

- input/pages/packaging.md
https://jira.hl7.org/browse/FHIR-45438
> Remove conformance requirement 6.5

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45873
> run-on sentence change

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45572
> FHIR-45572 text

- input/pages/data-model-standards-landscape.md
https://jira.hl7.org/browse/FHIR-45636
> FHIR-45636 removing STU note

- input/profiles/StructureDefinition-cqfm-appliesTo.json
clarify short description for appliesTo extension
> FHIR-46387

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45574
> FHIR-45574

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45571
> FHIR-45571 adding link

- input/pages/using-cql.md
https://jira.hl7.org/browse/FHIR-45389
> data model language/link change

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45881
> Fhir 45881

- input/profiles/StructureDefinition-publishable-measure-cqfm.json
https://jira.hl7.org/browse/FHIR-45361
> rationale changes

- input/pages/using-cql.md
https://jira.hl7.org/browse/FHIR-45435
> Editorial corrections to opening sentence

- input/profiles/StructureDefinition-cqfm-populationBasis.json
https://jira.hl7.org/browse/FHIR-45563
> fixing spacing

- input/pages/using-cql.md
New PR for FHIR-45885
https://jira.hl7.org/browse/FHIR-45885
> FHIR-45885

- archived/profiles/StructureDefinition-device-softwaresystem-cqfm.json
- archived/resources/examples/device-software-system-example.json
- input/pages/profiles.md
https://jira.hl7.org/browse/FHIR-45917
> Changing CQFMDevice to CRMI version

- input/profiles/StructureDefinition-publishable-measure-cqfm.json
Put includeInReportType extension back in CQFMPublishableMeasure
> FHIR-46462

- input/pages/composite-measures.md
- input/pages/glossary.md
- input/pages/index.md
- input/pages/introduction.md
- input/pages/measure-conformance.md
New PR with FHIR-45692 changes
> FHIR-45692 redone

- input/cqfmeasures.xml
Reference to archived example was causing genonce issues
https://jira.hl7.org/browse/FHIR-45917
> removing reference to archived example

- input/profiles/StructureDefinition-publishable-measure-cqfm.json
https://jira.hl7.org/browse/FHIR-47767
> FHIR-47767 CQMF Publishable Measure Profile Measure.status Fixed to Active

- input/pages/measure-conformance.md
https://jira.hl7.org/browse/FHIR-45466
> adding to table FHIR-45466
